# server 配置主要是go的http配置
server:
  host: 0.0.0.0
  port: 8081
  readTimeout: 10
  writeTimeout: 10

# redis配置
redis:
  host: redis:6379
  password: 123456
  maxIdle: 30
  maxActive: 100
  idleTimeout: 10
